# edge_agent/configs/default.yaml
resident:
  resident_id: "CB-001"
  name: "A 어르신"

source:
  video: 0
  audio: null
  ppg_csv: "edge_agent/examples/sample_ppg.csv"

thresholds:
  inactivity_sec: 10
  resp_brpm_low: 8
  resp_brpm_high: 28
  hr_bpm_low: 45
  hr_bpm_high: 120

alerts:
  mode: "none"        # "none"|"ble"|"sms"
  sms_gateway: null
  ble_address: null

storage:
  sqlite_path: "edge_agent/rva_events.db"

privacy:
  store_raw_frames: false
  store_features_only: true
